version: 0.1

phases:
  install:
    commands:
      - mkdir apis && cd apis && mkdir admin-panel
      - (cd apis/admin-panel && npm ixo) || (echo "CAT Test")
  build:
    commands:
      - echo Build started on `date`
  post_build:
    commands:
      - echo Build completed on `date`
      - echo $CODEBUILD_SRC_DIR
artifacts:
  files:
    

