version: 0.1

phases:
  install:
    commands:
      - mkdir apis && cd apis && mkdir admin-panel
      - cd apis/admin-panel && npm i
  build:
    commands:
      - echo Build started on `date`
  post_build:
    commands:
      - echo Build completed on `date`
      - echo apis/admin-panel/npm-debug.log
      - cat CODEBUILD_SRC_DIR/apis/admin-panel/npm-debug.log
      - cat apis/admin-panel/npm-debug.log
artifacts:
  files:
    

